### ISSUE TITLE
Cannot make new character!

### ISSUE THREAD

**Issue by mynameiscandyy** [ThaumRystra/DiceCloud1#66] opened 2017-05-11 00:49 UTC
Whenever i try to add a new character that I'd like to make no matter what it just never adds. I click add and it just closes. I put different names, longer names, shorter names, leaving it blank, or just putting jibberish in every line. Help? Wanna make some new characters.

**Comment by rperce** [comment] 2017-05-11 00:57
Issue confirmed by one of my players.

**Comment by ThaumRystra** [comment] 2017-05-11 08:45
Looks like dialog stacks aren't using their results when closing, this will cause an issue with more than just characters. A fix is on the way.

**Closed** 2017-05-11 09:17 UTC
Labels: bug, high priority
